if('serviceWorker'in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
const statuses={'Утверждённый канон':'canon','Рабочая идея':'draft','Новое предложение':'new','Требует уточнения':'warn'};
const sceneFields=['номер','название','сюжетный блок','время','место','главный персонаж','участники','краткое содержание','эмоциональная цель','последствия','связь с предыдущей и следующей сценой','заметки автора','вопросы без ответа','статус записи'];
const charFields=['имя','род / статус','возраст','внешность','характер','сильные стороны','слабости','страхи','травмы','желания','отношения','путь','боевое искусство','важные сцены','развитие по книге','важные предметы','канон','рабочие идеи','требует уточнения'];
const loreFolders=['мир и история','страны и города','Нингард','районы','организации','религия','роды','паспорта и статус','еретики','болезни','законы и наказания','важные предметы','пророчества','здания, мосты, статуи, архивы, лазареты','Новое / требует уточнения'];
const pathNames=['Архивы','Стражи','Лазаретные Хранители','Путь Образа и Слова'];const pathFields=['цель','обучение','наставники','ученики','правила','символы','одежда','конфликты','сцены','заметки'];const martialFields=['название','философия','история','сильные стороны','опасности','запреты','приёмы','носители','сцены, где используется','заметки и неразрешённое'];const holidayFields=['название','смысл','происхождение','традиции','символы','важные предметы','приметы','визуальная атмосфера','сцены, связанные с праздником','вопросы без ответа'];const issueFields=['тип','заголовок','описание','связанные записи','статус'];const relFields=['персонаж','тип связи','с кем','связанные сцены','заметки'];const relTypes=['дружба','любовь','ревность','конфликт','семья','долг','страх','тайна','вражда','уважение'];
const empty=fs=>Object.fromEntries(fs.map(f=>[f,'']));const seed=()=>({scenes:[],characters:[],lore:loreFolders.map(name=>({id:crypto.randomUUID(),name,pages:[]})),paths:pathNames.map(name=>({id:crypto.randomUUID(),name,...empty(pathFields)})),martial:[],holidays:[],relations:[],issues:[]});let data;try{data=JSON.parse(localStorage.archiveSoul)||seed()}catch{data=seed()}let tab='home',q='';const save=()=>localStorage.archiveSoul=JSON.stringify(data);const $=s=>document.querySelector(s);const el=(t,c='',h='')=>{let e=document.createElement(t);e.className=c;e.innerHTML=h;return e};
function field(o,f,big=false){let l=el('label','field',`<span>${f}</span>`),i=f==='статус записи'?el('select'):el(big?'textarea':'input');if(f==='статус записи')Object.keys(statuses).forEach(s=>i.add(new Option(s,s)));i.value=o[f]||'';i.placeholder='Заполнить позже';i.oninput=()=>{o[f]=i.value;save()};l.append(i);return l}
function editor(o,fields,onDelete){let c=el('div','card'),top=el('div','cardTop',`<b>${o.название||o.имя||o.name||o.заголовок||'Пустая карточка'}</b>`),d=el('button','danger','Удалить');d.onclick=()=>confirm('Удалить запись?')&&onDelete();top.append(d);c.append(top,...fields.map((f,i)=>field(o,f,i>3)));if(o['статус записи'])c.append(el('span','badge '+statuses[o['статус записи']],o['статус записи']));return c}
function list(title,key,fields,drag=false){let s=el('section','section'),head=el('div','sectionHead',`<h2>${title}</h2>`),add=el('button','','＋ Добавить');add.onclick=()=>{data[key].push({id:crypto.randomUUID(),...empty(fields),...(key==='scenes'?{'статус записи':'Рабочая идея'}:{})});save();render()};head.append(add);s.append(head);if(!data[key].length)s.append(el('p','empty','Пока нет записей. Создайте пустой шаблон и заполните его позже.'));let stack=el('div','stack');data[key].forEach((o,i)=>{let det=el('details','details'),sum=el('summary','',`<span>${o.номер?o.номер+'. ':''}${o.название||o.имя||o.заголовок||'Пустая карточка'}</span>`);det.append(sum);if(drag){let order=el('div','order'),up=el('button','','Выше'),down=el('button','','Ниже');up.disabled=i===0;down.disabled=i===data[key].length-1;up.onclick=()=>{data[key].splice(i-1,0,data[key].splice(i,1)[0]);save();render()};down.onclick=()=>{data[key].splice(i+1,0,data[key].splice(i,1)[0]);save();render()};order.append(up,down);det.append(order)}det.append(editor(o,fields,()=>{data[key]=data[key].filter(x=>x.id!==o.id);save();render()}));stack.append(det)});s.append(stack);return s}
function all(){return Object.entries(data).flatMap(([k,v])=>Array.isArray(v)?v.flatMap(x=>x.pages?[x,...x.pages]:[x]).map(x=>({k,x})):[])}function download(name,type,text){let a=el('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()}
function render(){let r=$('#root');r.innerHTML='';let main=el('main'),hero=el('div','hero','<h1>Архив Разбитой души</h1><p>Сцены, люди, память и всё, что ещё нельзя назвать истиной</p>'),search=el('div','search','⌕ '),inp=el('input');inp.placeholder='Поиск по персонажу, сцене, лору, месту, пути, статусу или слову';inp.value=q;inp.oninput=e=>{q=e.target.value;render()};search.append(inp);hero.append(search);main.append(hero);if(q){let sec=el('section','section','<h2>Поиск</h2>');all().filter(({x})=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).forEach(({k,x})=>sec.append(el('div','card',`<b>${x.название||x.имя||x.name||x.заголовок||'Запись'}</b><br><small>${k}</small>`)));main.append(sec)}
if(tab==='home'){let sec=el('section','section'),quick=el('div','quick');[['Новая сцена','scenes',sceneFields],['Новый персонаж','characters',charFields],['Новая запись лора','lore'],['Неразрешённое','issues',issueFields]].forEach(([txt,k,fs])=>{let b=el('button','',txt);b.onclick=()=>{if(fs)data[k].push({id:crypto.randomUUID(),...empty(fs)});tab=k;save();render()};quick.append(b)});let stats=el('div','stats');[['сцен',data.scenes.length],['персонажей',data.characters.length],['записей лора',data.lore.reduce((a,f)=>a+f.pages.length,0)],['нерешённых вопросов',data.issues.length]].forEach(([k,v])=>stats.append(el('div','card',`<strong>${v}</strong><br><span>${k}</span>`)));sec.append(quick,stats);main.append(sec)}
if(tab==='scenes'){let tl=el('div','timeline');data.scenes.forEach((s,i)=>tl.append(el('button','',s.номер||i+1)));main.append(tl,list('Карта сцен','scenes',sceneFields,true))}if(tab==='characters')main.append(list('Персонажи','characters',charFields));if(tab==='martial')main.append(list('Боевые искусства','martial',martialFields));if(tab==='holidays')main.append(list('Праздники и традиции','holidays',holidayFields));if(tab==='issues')main.append(list('Неразрешённое','issues',issueFields));if(tab==='paths')main.append(list('Пути','paths',['name',...pathFields]));
if(tab==='lore'){let sec=el('section','section','<h2>Лор мира</h2>');data.lore.forEach(f=>{let d=el('details','details',`<summary><span>${f.name}</span></summary>`),b=el('button','','＋ Новая страница');b.onclick=()=>{f.pages.push({id:crypto.randomUUID(),название:'',заметки:''});save();render()};d.append(b);f.pages.forEach(p=>d.append(editor(p,['название','заметки'],()=>{f.pages=f.pages.filter(x=>x.id!==p.id);save();render()})));sec.append(d)});main.append(sec)}
if(tab==='relations'){let sec=el('section','section','<h2>Связи и отношения</h2>'),map=el('div','relmap');data.characters.forEach(c=>map.append(el('div','node',c.имя||'Персонаж')));sec.append(map,list('Карточки связей','relations',relFields),el('p','empty','Типы связей: '+relTypes.join(', ')+'. При нажатии на карточку персонажа можно описать его связи и связанные сцены.'));main.append(sec)}
if(tab==='backup'){let sec=el('section','section','<h2>Резервная копия</h2>'),quick=el('div','quick');let ej=el('button','','Экспорт JSON');ej.onclick=()=>download('arhiv-razbitoi-dushi.json','application/json',JSON.stringify(data,null,2));let im=el('label','button','Импорт JSON'),fi=el('input');fi.type='file';fi.accept='application/json';fi.hidden=true;fi.onchange=()=>{let fr=new FileReader();fr.onload=()=>{data=JSON.parse(fr.result);save();render()};fr.readAsText(fi.files[0])};im.append(fi);let txt=el('button','','Экспорт TXT');txt.onclick=()=>download('zametki-razbitoi-dushi.txt','text/plain',all().map(({k,x})=>'['+k+']\n'+Object.entries(x).filter(([p])=>p!=='id').map(([p,v])=>p+': '+v).join('\n')).join('\n\n---\n\n'));let del=el('button','danger','Удалить данные');del.onclick=()=>confirm('Удалить всю локальную базу?')&&(localStorage.removeItem('archiveSoul'),location.reload());quick.append(ej,im,txt,del);sec.append(quick,el('p','empty','Автоматическое локальное сохранение включено.'));main.append(sec)}
r.append(main);let nav=el('nav');[['home','Главная'],['scenes','Карта сцен'],['characters','Персонажи'],['lore','Лор мира'],['paths','Пути'],['martial','Боевые искусства'],['holidays','Праздники'],['relations','Связи'],['issues','Неразрешённое'],['backup','Резерв']].forEach(([id,label])=>{let b=el('button',tab===id?'active':'',label);b.onclick=()=>{tab=id;render()};nav.append(b)});r.append(nav)}render();
